#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-svc
spec:
  type: ClusterIP
  selector:
    app: juice-shop
  ports:
    - port: 8080
      targetPort: 3000
      
---
#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juice-shop-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: juice-shop-svc
            port:
              number: 8080
              
              
              
              
              
      
